TaskApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TaskApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TaskApplication/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskApplication.DTO.Classes;

namespace TaskApplication.Controllers
{
    public class TaskController : Controller
    {
        TaskApplication.BLL.Classes.TaskBLL objTaskBLL = new TaskApplication.BLL.Classes.TaskBLL();

        // GET: Task
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search(TaskDTO pTask)
        {
            var objReturn = objTaskBLL.Search(pTask);

            return PartialView("PartialTaskTable", objReturn);
        }

        public ActionResult Update(TaskDTO pTask)
        {
            if (objTaskBLL.Update(pTask))
            {
                //Sucesso em atualizar a Task, retornar para a tela de inicio
                return View("Index");
            }
            else
            {
                // Erro ao atualizar a Task, direcionar para a página de erro
                return View("Erro");
            }
        }

        public ActionResult Delete(int pTaskID)
        {
            if (objTaskBLL.Delete(pTaskID))
            {
                //Sucesso em deletar a Task, retornar para a tela de inicio
                return View("Index");
            }
            else
            {
                // Erro ao atualizar a Task, direcionar para a página de erro
                return View("Erro");
            }
        }

        public ActionResult Save(TaskDTO pTask)
        {
            if (objTaskBLL.Save(pTask))
            {
                //Sucesso em salvar a Task, retornar para a tela de inicio
                return View("Index");
            }
            else
            {
                // Erro ao atualizar a Task, direcionar para a página de erro
                return View("Erro");
            }
        }

    }
}

TaskApplication/Controllers/TaskRESTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using TaskApplication.DTO.Classes;

namespace TaskApplication.Controllers
{
    public class TaskRESTController : ApiController
    {
        TaskApplication.BLL.Classes.TaskBLL objTaskBLL = new TaskApplication.BLL.Classes.TaskBLL();

        // GET: api/TaskREST
        //[AcceptVerbs("GET")]
        public IEnumerable<TaskDTO> Get()
        {
            return objTaskBLL.Search(new TaskDTO() {});
        }

        // GET: api/TaskREST/5
        //[AcceptVerbs("GET")]
        public TaskDTO Get(int id)
        {
            return objTaskBLL.Get(id);
        }

        // POST: api/TaskREST
        //[AcceptVerbs("POST")]
        public void Post(TaskDTO pTask)
        {
            objTaskBLL.Save(pTask);
        }

        // PUT: api/TaskREST/5
        //[AcceptVerbs("PUT")]
        public void Put(TaskDTO pTask)
        {
            //Também poderia utilizar o Save
            objTaskBLL.Update(pTask);
        }

        // DELETE: api/TaskREST/5
        //[AcceptVerbs("DELETE")]
        public void Delete(int id)
        {
            objTaskBLL.Delete(id);
        }
    }
}

TaskApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TaskApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TaskApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TaskApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aplicação de Exemplo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Tasks", "Index", "Task", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TaskApplication/Views/Task/Index.cshtml
@model TaskApplication.DTO.Classes.TaskDTO


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Task</h2>

<div>

    @using (Html.BeginForm("Search", "Task", FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "formSearch" }))
    {
        <div class="form-row">
            <div class="col-md-4">
                @Html.LabelFor(m => m.StartDate)
                @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control", @type = "date" })
            </div>

            <div class="col-md-4">
                @Html.LabelFor(m => m.EndDate)
                @Html.TextBoxFor(m => m.EndDate, new { @class = "form-control", @type = "date" })
            </div>
        </div>

        <div style="padding-top:15px">
            <button type="button" class="btn btn-default" id="btnSearch" title="Pesquisar"><i class="fas fa-search"></i><span>Pesquisar</span></button>
            <button type="button" class="btn btn-default" id="btnCreate" title="Pesquisar"><i class="fas fa-search"></i><span>Novo</span></button>
        </div>

        <div id="partialTableTask" style="padding-top:15px">
            @Html.Partial("PartialTaskTable", new List<TaskApplication.DTO.Classes.TaskDTO>())
        </div>
    }

    @Html.Partial("PartialTaskCreate", new TaskApplication.DTO.Classes.TaskDTO())
</div>


@section Scripts {
    <script type="text/javascript">

    $(document).ready(function(){
        Search();
    });

    $(document).on('click', "#btnSearch" ,function () {
        Search();
    });

    $(document).on('click', "#btnCreate", function () {
        //$("#formCreateTask").trigger("reset");
        ClearForm();

        $("#ModalCreateTask").modal();
    });

    $(document).on('click', "[name='btnUpdate']", function () {
        var id = $(this).attr('data-id');
        debugger
        //Preferi fazer no fronte para não fazer uma nova consulta no SQL
        var name = $(this).closest('tr').find('[name="tdName"]').text();
        var description = $(this).closest('tr').find('[name="tdDescription"]').text();
        var status = $(this).closest('tr').find('[name="tdStatus"]').text();

        $('#TaskID').val(id);
        $('#Name').val(name);
        $('#Description').val(description);
        $("#Status").val(status);


        $("#ModalCreateTask").modal();
    });

    $(document).on('click', ".modal-close", function () {
        $("#ModalCreateTask").modal('hide');
    });

        function ClearForm() {
            $('#TaskID').val("");
            $('#Name').val("");
            $('#Description').val("");
            $("#Status").val("Ativo");
        }

    function Search() {
            var form = $('#formSearch').serialize();

            $.ajax({
                type: "POST",
                url: "@Url.Action("Search","Task")",
                data: form,
                success: function (data) {
                    $('#partialTableTask').html(data);
                }
            });
        }

    </script>
}

TaskApplication/Views/Task/PartialTaskCreate.cshtml
@model TaskApplication.DTO.Classes.TaskDTO


<div class="modal" id="ModalCreateTask" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                Cadastrar novo motivo
            </div>
            @using (Html.BeginForm("Save", "Task", FormMethod.Post, new { id = "formCreateTask" }))
            {
            <div class="modal-body">
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.TaskID)

                <div class="form-group">
                    <label class="control-label" for="Detalhes">Nome</label>
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control mw-100", @required = "required" })
                </div>

                <div class="form-group">
                    <label class="control-label" for="Descricao">Descrição</label>
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control mw-100", @required = "required" })
                </div>

                <div class="form-group">
                    <label class="control-label" for="Descricao">Status</label>
                    <select class="form-control" name="Status" id="Status">
                        <option value="@TaskApplication.DTO.Enum.TaskEnum.Status.Ativo" selected> Ativo </option>
                        <option value="@TaskApplication.DTO.Enum.TaskEnum.Status.Concluido"> Concluído </option>
                    </select>
                    @*@Html.EnumDropDownListFor(x => x.Status, new { @class= "form-control" } )*@
                </div>


            </div>
                <div class="modal-footer">
                    <div class="btn-box">
                        <button type="button" class="modal-action modal-close btn btn-large-gray" data-dismiss="modal" title="Fechar"><i class="fas fa-ban"></i><span>Fechar</span></button>
                        <button type="submit" class="modal-action btn" title="Salvar"><i class="fas fa-save"></i><span>Salvar</span></button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

TaskApplication/Views/Task/PartialTaskTable.cshtml
@model List<TaskApplication.DTO.Classes.TaskDTO>

@{
    Layout = null;
}

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Data Criação</th>
            <th>Status</th>
            <th>Ações</th>
        </tr>
    </thead>

    <tbody>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td name="tdName">@item.Name</td>
                    <td name="tdDescription">@item.Description</td>
                    <td>@item.DateCreation.ToLocalTime()</td>
                    <td name="tdStatus">@item.Status.ToString()</td>
                    <td>
                        <button type="button" class="btn btn-default" data-id="@item.TaskID" name="btnUpdate">
                            <i class="tiny icon fas fa-history" title="Atualizar"></i>
                            Atualizar
                        </button>
                        @Html.ActionLink("Delete", "Delete","Task", new { pTaskID = item.TaskID }, new { @class= "btn btn-default" })
                    </td>
                </tr>
            }
        }

    </tbody>
</table>